project:
  type: website
  output-dir: docs

website:
  title: "Fares Alkorani"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: Resume - March 18.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

